In [2]:
import numpy as np

# Define two vectors
a = np.array([2, 3])
b = np.array([4, 1])

In [3]:
# Basic operations
add = a + b
sub = a - b
dot = np.dot(a, b)

print("a + b =", add)
print("a - b =", sub)
print("Dot Product =", dot)

a + b = [6 4]
a - b = [-2  2]
Dot Product = 11


In [4]:

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])


In [5]:
# Operations
C = np.dot(A, B)
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A x B =\n", C)
print("Determinant of A =", det_A)
print("Inverse of A:\n", inv_A)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[2 0]
 [1 2]]
A x B =
 [[ 4  4]
 [10  8]]
Determinant of A = -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
A = np.array([[2, 1], [1, 1]])
b = np.array([5, 3])

# Solve for x
x = np.linalg.solve(A, b)

print("Solution (x, y) =", x)

Solution (x, y) = [2. 1.]
